In [1]:
import pandas as pd
import numpy as np

ImportError: Unable to import required dependencies:
numpy: No module named 'numpy'

In [16]:
data=pd.read_csv("./text_sentiment_analysis_dataset.csv")
data.head()

   Unnamed: 0                                               text  label
0           0      i just feel really helpless and heavy hearted      4
1           1  ive enjoyed being able to slouch about relax a...      0
2           2  i gave up my internship with the dmrg and am f...      4
3           3                         i dont know i feel so lost      0
4           4  i am a kindergarten teacher and i am thoroughl...      4

In [17]:
data.shape

(416809, 3)

In [18]:
data.head()

   Unnamed: 0                                               text  label
0           0      i just feel really helpless and heavy hearted      4
1           1  ive enjoyed being able to slouch about relax a...      0
2           2  i gave up my internship with the dmrg and am f...      4
3           3                         i dont know i feel so lost      0
4           4  i am a kindergarten teacher and i am thoroughl...      4

In [19]:
data.drop(columns=['Unnamed: 0'], inplace=True)

In [20]:
data.shape

(416809, 2)

In [21]:
# Calculate the total number of entries
total_entries = len(data)

# Calculate the count of each emotion
emotion_counts = data['label'].value_counts()
print(emotion_counts)
# Calculate the percentage of each emotion
emotion_percentages = (emotion_counts / total_entries) * 100

# Print the percentage of each emotion
print(emotion_percentages)

label
1    141067
0    121187
3     57317
4     47712
2     34554
5     14972
Name: count, dtype: int64
label
1    33.844519
0    29.074948
3    13.751383
4    11.446970
2     8.290128
5     3.592053
Name: count, dtype: float64

In [22]:
# we need to map the data so we can get the good visualization
emotion_map = {
    0: 'sadness',
    1: 'joy',
    2: 'love',
    3: 'anger',
    4: 'fear',
    5: 'surprise'

}

data['label'] = data['label'].map(emotion_map)

In [23]:
data.head()

                                                text    label
0      i just feel really helpless and heavy hearted     fear
1  ive enjoyed being able to slouch about relax a...  sadness
2  i gave up my internship with the dmrg and am f...     fear
3                         i dont know i feel so lost  sadness
4  i am a kindergarten teacher and i am thoroughl...     fear

In [ ]:
!pip uninstall numpy scipy
!pip install numpy scipy

In [24]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [ ]:
# #function to get part of speech tag
# def getPOS(pos):
#   wordnet_pos='v'

#   if pos.startswith('J'):
#         wordnet_pos = 'a'  # Adjective
#   elif pos.startswith('V'):
#         wordnet_pos = 'v'  # Verb
#   elif pos.startswith('N'):
#         wordnet_pos = 'n'  # Noun
#   elif pos.startswith('R'):
#         wordnet_pos = 'r'  # Adverb
#   else:
#         wordnet_pos = 'n'  # Default to noun

#   return wordnet_pos

In [11]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

stopwords_set = set(stopwords.words('english'))
emoji_pattern = re.compile('(?::|;|=)(?:-)?(?:\)|\(|D|P)')

def preprocessing(text):


    # Remove HTML tags
    text = re.sub('<[^>]*>', '', text)

    # Remove URLs
    text = re.sub(r'http\S+', '', text)

    # Extract emojis
    emojis = emoji_pattern.findall(text)

    # Remove non-alphanumeric characters, convert to lowercase, and join emojis
    text = re.sub('[\W+]', ' ', text.lower()) + ' '.join(emojis).replace('-', '')



   # Apply stemming and remove stopwords
    prter = PorterStemmer()
    text = [prter.stem(word) for word in text.split() if word not in stopwords_set]

    processed_text= " ".join(text)
    return processed_text

NameError: name 'nltk' is not defined

In [12]:
# Define a mapping dictionary
label_mapping = {'sadness':0, 'joy':1, 'love':2, 'anger':3, 'fear':4,'surprise':5}

# Rename the 'Label' column using the mapping dictionary
data['label'] = data['label'].map(label_mapping)

In [13]:
data.head(10)

                                                text  label
0      i just feel really helpless and heavy hearted      4
1  ive enjoyed being able to slouch about relax a...      0
2  i gave up my internship with the dmrg and am f...      4
3                         i dont know i feel so lost      0
4  i am a kindergarten teacher and i am thoroughl...      4
5         i was beginning to feel quite disheartened      0
6  i would think that whomever would be lucky eno...      2
7  i fear that they won t ever feel that deliciou...      1
8  im forever taking some time out to have a lie ...      5
9  i can still lose the weight without feeling de...      0

In [14]:
data['text'] = data['text'].apply(lambda x: preprocessing(x))

NameError: name 'preprocessing' is not defined

In [ ]:
pip install keras

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: keras in c:\users\moin\appdata\roaming\python\python311\site-packages (2.15.0)
Note: you may need to restart the kernel to use updated packages.

DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import LSTM, Dense,Dropout
from keras.utils import to_categorical
from keras.layers import *

WARNING:tensorflow:From C:\Users\Moin\AppData\Roaming\Python\Python311\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [17]:
vocab_size = len(set(" ".join(data['text']).split()))
vocab_size

51874

In [ ]:
# #one hot encoding of text
# voc_size=51874
# x_onehot=[one_hot(words,voc_size)for words in data['text']]

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
# TF-IDF Vectorization
tfidf=TfidfVectorizer(strip_accents=None,lowercase=False,preprocessor=None,use_idf=True,norm='l2',smooth_idf=True,max_features=1000)
x = tfidf.fit_transform(data.text).toarray()
y = data.label.values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [19]:
x_train.shape

(333447, 1000)

In [21]:
# Reshape the input data for LSTM
# LSTM expects input in the shape of (samples, time steps, features)
# In this case, samples would be the number of documents, time steps would be 1 (since each document is treated independently), and features would be the TF-IDF values
x_train_lstm = np.reshape(x_train, (x_train.shape[0], 1, x_train.shape[1]))
x_test_lstm = np.reshape(x_test, (x_test.shape[0], 1, x_test.shape[1]))

In [22]:
x_train_lstm.shape

(333447, 1, 1000)

In [23]:
from keras.layers import Input

# Define input layer explicitly
input_layer = Input(shape=(1, x_train.shape[1]))

# Define LSTM model
model = Sequential()
model.add(input_layer)
model.add(LSTM(units=128))
model.add(Dense(units=6, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print(model.summary())

WARNING:tensorflow:From C:\Users\Moin\AppData\Roaming\Python\Python311\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

WARNING:tensorflow:From C:\Users\Moin\AppData\Roaming\Python\Python311\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 128)               578048

 dense (Dense)               (None, 6)                 774

=================================================================
Total params: 578822 (2.21 MB)
Trainable params: 578822 (2.21 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None

In [24]:
### Finally Training
# Train the model
model.fit(x_train_lstm,y_train,validation_data=(x_test_lstm,y_test),batch_size=64,epochs=10)

Epoch 1/10
WARNING:tensorflow:From C:\Users\Moin\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\Moin\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

5211/5211 [==============================] - 104s 18ms/step - loss: 0.4645 - accuracy: 0.8301 - val_loss: 0.3883 - val_accuracy: 0.8508
Epoch 2/10
5211/5211 [==============================] - 120s 23ms/step - loss: 0.3749 - accuracy: 0.8543 - val_loss: 0.3758 - val_accuracy: 0.8522
Epoch 3/10
5211/5211 [==============================] - 114s 22ms/step - loss: 0.3613 - accuracy: 0.8562 - val_loss: 0.3663 - val_accuracy: 0.8526
Epoch 4/10
5211/5211 [==============================] - 118s 23ms/step - loss: 0.3509 - accuracy: 0.8577 - val_loss: 0.3621 - val_accuracy: 0.8521
Epoch 5/10
5211/5211 [==============================] - 119s 23ms/step - loss: 0.3414 - accuracy: 0.8603 - val_loss: 0.3584 - val_accuracy: 0.8524
Epoch 6/10
5211/5211 [==============================] - 85s 16ms/step - loss: 0.3323 - accuracy: 0.8631 - val_loss: 0.3541 - val_accuracy: 0.8517
Epoch 7/10
5211/5211 [==============================] - 73s 14ms/step - loss: 0.3229 - accuracy: 0.8660 - val_loss: 0.3529 - val_accuracy: 0.8515
Epoch 8/10
5211/5211 [==============================] - 72s 14ms/step - loss: 0.3131 - accuracy: 0.8688 - val_loss: 0.3535 - val_accuracy: 0.8500
Epoch 9/10
5211/5211 [==============================] - 74s 14ms/step - loss: 0.3026 - accuracy: 0.8723 - val_loss: 0.3532 - val_accuracy: 0.8497
Epoch 10/10
5211/5211 [==============================] - 74s 14ms/step - loss: 0.2915 - accuracy: 0.8768 - val_loss: 0.3549 - val_accuracy: 0.8483

In [25]:
# Evaluate the model
score = model.evaluate(x_test_lstm, y_test)
print('Test Accuracy:', score[1])

2606/2606 [==============================] - 10s 3ms/step - loss: 0.3549 - accuracy: 0.8483
Test Accuracy: 0.8483121991157532

In [36]:
def prediction(comment):
    preprocessed_comment = preprocessing(comment)
    print("Preprocessed Comment:", preprocessed_comment)
    comment_list = [preprocessed_comment]
    comment_vector = tfidf.transform(comment_list).toarray()
    # print("TF-IDF Vector:", comment_vector)

    # Reshape TF-IDF vector for LSTM input
    comment_vector_lstm = np.reshape(comment_vector, (comment_vector.shape[0], 1, comment_vector.shape[1]))

    decision_scores = model.predict(comment_vector_lstm)
    print("Raw Decision Scores:", decision_scores)
    predicted_class = np.argmax(decision_scores)

    emotion_mapping = {0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}
    predicted_emotion = emotion_mapping[predicted_class]
    print("Predicted Emotion:", predicted_emotion)

# Example usage:
prediction('The injustice of the situation makes my blood boil')

Preprocessed Comment: injustic situat make blood boil
1/1 [==============================] - 0s 36ms/step
Raw Decision Scores: [[0.07305032 0.20850755 0.01203458 0.5247235  0.16459449 0.01708963]]
Predicted Emotion: anger

In [34]:
model.save('sentiment_model_v2.h5')

C:\Users\Moin\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [35]:
import pickle
pickle.dump(model,open('model_v2.pkl','wb'))
pickle.dump(tfidf,open('tfidf_v2.pkl','wb'))

In [ ]:
message=data['text'].iloc[5]
print(message)
x_onehot[5]

begin feel quit dishearten

[4665, 28215, 50749, 34786]

In [ ]:
#padding of one_hot encoded text
sent_length=130
embedded_docs=pad_sequences(x_onehot,padding='post',maxlen=sent_length)
print(embedded_docs)

[[28215 26292 47945 ...     0     0     0]
 [38132  9126 18699 ...     0     0     0]
 [21239 13806 15791 ...     0     0     0]
 ...
 [28215 32203 51267 ...     0     0     0]
 [28215 12972 25980 ...     0     0     0]
 [19442 13445 49351 ...     0     0     0]]

In [ ]:
embedding_vector_features = 140  # Feature representation neurons in hidden layer
sent_length=130
voc_size=51874
# Define the model
model = Sequential()

# Add an embedding layer
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))

# Add a bidirectional GRU layer with 128 units
model.add(Bidirectional(LSTM(128)))

# Add batch normalization layer
model.add(BatchNormalization())

# Add dropout regularization
model.add(Dropout(0.5))

# Add a dense layer with 64 units and ReLU activation
model.add(Dense(64, activation='relu'))

# Add dropout regularization
model.add(Dropout(0.5))

# Add the output layer with 6 units for 6 labels and softmax activation
model.add(Dense(6, activation='softmax'))

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Display the model summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 130, 140)          7262360

 bidirectional_1 (Bidirecti  (None, 256)               275456
 onal)

 batch_normalization_1 (Bat  (None, 256)               1024
 chNormalization)

 dropout_2 (Dropout)         (None, 256)               0

 dense_2 (Dense)             (None, 64)                16448

 dropout_3 (Dropout)         (None, 64)                0

 dense_3 (Dense)             (None, 6)                 390

=================================================================
Total params: 7555678 (28.82 MB)
Trainable params: 7555166 (28.82 MB)
Non-trainable params: 512 (2.00 KB)
_________________________________________________________________

In [ ]:
X_final=np.array(embedded_docs)
Y_final=np.array(data['label'])

In [ ]:
data['label'].shape

(416809,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, Y_final, test_size=0.3, random_state=30)

In [ ]:

X_train.shape, X_test.shape

((291766, 130), (125043, 130))

In [ ]:
### Finally Training
# Train the model
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=100,callbacks=[EarlyStopping(patience=3)])

Epoch 1/10
 574/2918 [====>.........................] - ETA: 31:06 - loss: 0.7271 - accuracy: 0.7415

In [ ]:
# Evaluate the model
score = model.evaluate(X_test, y_test)
print('Test Accuracy:', score[1])

3908/3908 [==============================] - 176s 45ms/step - loss: 0.1430 - accuracy: 0.9281
Test Accuracy: 0.928128719329834

In [ ]:
# Save the model
model.save("sentiment_model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [ ]:
import pickle
pickle.dump(model,open('sentiment_model.pkl','wb'))
!ls

drive  sample_data  sentiment_model.h5	sentiment_model.pkl

In [ ]:

# function to perform one hot encoding and padding
def oneHotEncoding(text):
     # perform one hot encoding

    vocab_size=24568
    oneHotEncodedText=[one_hot(text,vocab_size)]
    print("One Hot Encoded Text:",oneHotEncodedText)
#     # perform padding of encoded text
    sent_length=130
    paddedSequence=pad_sequences(oneHotEncodedText,padding='post',maxlen=sent_length)
    print("Padded encoded text",paddedSequence)
    return paddedSequence

In [ ]:
def preprocessing2(text):


    # Remove HTML tags
    text = re.sub('<[^>]*>', '', text)

    # Remove URLs
    text = re.sub(r'http\S+', '', text)

    # Extract emojis
    emojis = emoji_pattern.findall(text)

    # Remove non-alphanumeric characters, convert to lowercase, and join emojis
    text = re.sub('[\W+]', ' ', text.lower()) + ' '.join(emojis).replace('-', '')
    # lower case conversion
    text=text.lower()

    # Tokenization, remove stopwords and lemmatization


    lemmatizer=WordNetLemmatizer()
    words=word_tokenize(text)
    pos_tags = nltk.pos_tag(words)
    lemmatized_words = [lemmatizer.lemmatize(word, pos=getPOS(pos)) for word, pos in pos_tags if word.lower() not in set(stopwords.words('english'))]

    processed_text=' '.join(lemmatized_words)
    print("Processed Text:",processed_text)
    oneHotEncodedText=oneHotEncoding(processed_text)
    return oneHotEncodedText

In [ ]:
import numpy as np

def analyze_sentiment(comment):
    print("Comment:", comment)
    sentiments = []

    # Preprocess the comment and convert it to one-hot encoded text
    oneHotEncodedText = preprocessing2(comment)

    # Get the decision scores from the model
    decision_scores = model.predict(oneHotEncodedText)
    print("Raw Decision Scores: [Negative, Positive, Neutral]", decision_scores)

    # Get the indices of top 3 predicted classes
    top_3_indices = np.argsort(-decision_scores[0])[:3]  # Select the top 3 indices
    print("Top 3 predicted class indices:", top_3_indices)

    # Sum of probabilities of the top 3 sentiments
    sum_probabilities = np.sum(decision_scores)

    # Map the predicted class indices to sentiments
    label_mapping = {0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}
    for index in top_3_indices:
        sentiment = label_mapping[int(index)]
        probability = decision_scores[0][int(index)]  # Access the probability corresponding to the index
        percentage = (probability / sum_probabilities) * 100
        sentiments.append((sentiment, probability, percentage))

    return sentiments

In [ ]:
analyze_sentiment("i remember feeling after the third bong hit that i was being pressured into this.")

Comment: i remember feeling after the third bong hit that i was being pressured into this.

NameError: name 're' is not defined